# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'retoCP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for retoCP

pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'PayULite'

end
